version: '3'
services:
  frontend:
    build: 
      context: './react-docker'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend-container
    environment:
      - WATCHPACKPOLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./react-docker:/app
    depends_on:
      - backend
  backend:
    build: 
      context: './node-docker'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: backend-container
    networks: 
      - mern-stack-network
    volumes:
      - ./node-docker:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=ecomm
networks:
  mern-stack-network:
volumes:
  mongoData: